CREATE DATABASE segreteria;

CREATE TABLE studenti(
	id SERIAL PRIMARY KEY,
	nome VARCHAR(50) NOT NULL,
	matricola VARCHAR(50) UNIQUE NOT NULL,
	diplomato BOOLEAN DEFAULT FALSE,
	creato_il TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);